// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var actions;
(function (actions) {
    actions[actions["getPage"] = 0] = "getPage";
})(actions || (actions = {}));
