// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var types;
(function (types) {
    types[types["server"] = 0] = "server";
    types[types["client"] = 1] = "client";
})(types || (types = {}));
