"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.actions = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var actions;
(function (actions) {
    actions[actions["getPage"] = 0] = "getPage";
})(actions || (exports.actions = actions = {}));
