"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.types = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var types;
(function (types) {
    types[types["server"] = 0] = "server";
    types[types["client"] = 1] = "client";
})(types || (exports.types = types = {}));
