// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { MRD } from './the-mrdname-space/mrd.js';
export { actions } from './the-mrdname-space/actions.js';
export { types } from './the-mrdname-space/types.js';
